extern InputGroup userInterfaceGeneral;
extern InputGroup userInterfaceSystem;
extern InputGroup userInterfaceEmulationSpeed;
extern InputGroup userInterfaceStates;
extern InputGroup userInterfaceVideoSettings;
