#define SUBORB_FKB_ESCAPE                0x01
#define SUBORB_FKB_F1                        0x02
#define SUBORB_FKB_F2                        0x03
#define SUBORB_FKB_F3                        0x04
#define SUBORB_FKB_F4                        0x05
#define SUBORB_FKB_F5                        0x06
#define SUBORB_FKB_F6                        0x07
#define SUBORB_FKB_F7                        0x08
#define SUBORB_FKB_F8                        0x09
#define SUBORB_FKB_F9                        0x0A
#define SUBORB_FKB_F10                        0x0B
#define SUBORB_FKB_F11                        0x0C
#define SUBORB_FKB_F12                        0x0D
#define SUBORB_FKB_PAUSE                0x0E
#define SUBORB_FKB_GRAVE                0x0F
#define SUBORB_FKB_1                        0x10
#define SUBORB_FKB_2                        0x11
#define SUBORB_FKB_3                        0x12
#define SUBORB_FKB_4                        0x13
#define SUBORB_FKB_5                        0x14
#define SUBORB_FKB_6                        0x15
#define SUBORB_FKB_7                        0x16
#define SUBORB_FKB_8                        0x17
#define SUBORB_FKB_9                        0x18
#define SUBORB_FKB_0                        0x19
#define SUBORB_FKB_MINUS                0x1A
#define SUBORB_FKB_EQUALS                0x1B
#define SUBORB_FKB_BACK                0x1C
#define SUBORB_FKB_INSERT                0x1D
#define SUBORB_FKB_HOME                0x1E
#define SUBORB_FKB_PRIOR                0x1F
#define SUBORB_FKB_NUMLOCK                0x20
#define SUBORB_FKB_DIVIDE                0x21
#define SUBORB_FKB_MULTIPLY        0x22
#define SUBORB_FKB_SUBTRACT        0x23
#define SUBORB_FKB_TAB                        0x24
#define SUBORB_FKB_Q                        0x25
#define SUBORB_FKB_W                        0x26
#define SUBORB_FKB_E                        0x27
#define SUBORB_FKB_R                        0x28
#define SUBORB_FKB_T                        0x29
#define SUBORB_FKB_Y                        0x2A
#define SUBORB_FKB_U                        0x2B
#define SUBORB_FKB_I                        0x2C
#define SUBORB_FKB_O                        0x2D
#define SUBORB_FKB_P                        0x2E
#define SUBORB_FKB_LBRACKET        0x2F
#define SUBORB_FKB_RBRACKET        0x30
#define SUBORB_FKB_RETURN                0x31
#define SUBORB_FKB_DELETE                0x32
#define SUBORB_FKB_END                        0x33
#define SUBORB_FKB_NEXT                0x34
#define SUBORB_FKB_NUMPAD7                0x35
#define SUBORB_FKB_NUMPAD8                0x36
#define SUBORB_FKB_NUMPAD9                0x37
#define SUBORB_FKB_ADD                        0x38
#define SUBORB_FKB_CAPITAL                0x39
#define SUBORB_FKB_A                        0x3A
#define SUBORB_FKB_S                        0x3B
#define SUBORB_FKB_D                        0x3C
#define SUBORB_FKB_F                        0x3D
#define SUBORB_FKB_G                        0x3E
#define SUBORB_FKB_H                        0x3F
#define SUBORB_FKB_J                        0x40
#define SUBORB_FKB_K                        0x41
#define SUBORB_FKB_L                        0x42
#define SUBORB_FKB_SEMICOLON        0x43
#define SUBORB_FKB_APOSTROPHE        0x44
#define SUBORB_FKB_NUMPAD4                0x45
#define SUBORB_FKB_NUMPAD5                0x46
#define SUBORB_FKB_NUMPAD6                0x47
#define SUBORB_FKB_LSHIFT                0x48
#define SUBORB_FKB_Z                        0x49
#define SUBORB_FKB_X                        0x4A
#define SUBORB_FKB_C                        0x4B
#define SUBORB_FKB_V                        0x4C
#define SUBORB_FKB_B                        0x4D
#define SUBORB_FKB_N                        0x4E
#define SUBORB_FKB_M                        0x4F
#define SUBORB_FKB_COMMA                0x50
#define SUBORB_FKB_PERIOD                0x51
#define SUBORB_FKB_SLASH                0x52
#define SUBORB_FKB_BACKSLASH        0x53
#define SUBORB_FKB_UP                        0x54
#define SUBORB_FKB_NUMPAD1                0x55
#define SUBORB_FKB_NUMPAD2                0x56
#define SUBORB_FKB_NUMPAD3                0x57
#define SUBORB_FKB_LCONTROL        0x58
#define SUBORB_FKB_LMENU                0x59
#define SUBORB_FKB_SPACE                0x5A
#define SUBORB_FKB_LEFT                0x5B
#define SUBORB_FKB_DOWN                0x5C
#define SUBORB_FKB_RIGHT                0x5D
#define SUBORB_FKB_NUMPAD0                0x5E
#define SUBORB_FKB_DECIMAL                0x5F

