//
//  OEGridView.h
//  OEGridViewDemo
//
//  Created by Faustino Osuna on 2/9/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import <Cocoa/Cocoa.h>
#import "OEGridViewCell.h"
#import "OEGridViewLayoutManager.h"
#import "OEGridViewFieldEditor.h"

#pragma mark -
@class OEGridView;

@protocol OEGridViewDelegate <NSObject>

@optional
- (void)selectionChangedInGridView:(OEGridView *)gridView;
- (void)gridView:(OEGridView *)gridView doubleClickedCellForItemAtIndex:(NSUInteger)index;
- (NSDragOperation)gridView:(OEGridView *)gridView validateDrop:(id<NSDraggingInfo>)sender;
- (NSDragOperation)gridView:(OEGridView *)gridView draggingUpdated:(id<NSDraggingInfo>)sender;
- (BOOL)gridView:(OEGridView *)gridView acceptDrop:(id<NSDraggingInfo>)sender;

@end

#pragma mark -
@protocol OEGridViewDataSource <NSObject>

@required
- (OEGridViewCell *)gridView:(OEGridView *)gridView cellForItemAtIndex:(NSUInteger)index;
- (NSUInteger)numberOfItemsInGridView:(OEGridView *)gridView;

@optional
- (NSView *)viewForNoItemsInGridView:(OEGridView *)gridView;
- (void)gridView:(OEGridView *)gridView willBeginEditingCellForItemAtIndex:(NSUInteger)index;
- (void)gridView:(OEGridView *)gridView didEndEditingCellForItemAtIndex:(NSUInteger)index;
- (id<NSPasteboardWriting>)gridView:(OEGridView *)gridView pasteboardWriterForIndex:(NSInteger)index;

@end

#pragma mark -
@interface OEGridView : NSView <OEGridViewLayoutManagerProtocol, NSDraggingSource, NSDraggingDestination>
{
@private
    OEGridLayer *_rootLayer;                        // Root layer, where all other layers are inserted into
    CALayer *_selectionLayer;                       // Selection box that appears when selecting multiple cells
    CALayer *_dragIndicationLayer;                  // A visual indication that a file is being dragged onto the grid view
    CALayer *_backgroundLayer;                      // A decorative background layer, the layer should return nil for -hitTest
    CALayer *_foregroundLayer;                      // A decorative foreground layer, the layer should return nil for -hitTest
    NSView *_noItemsView;                           // A decorative view when there are no items to show, e.g. blank slate

    NSSize _cellSize;                               // User defined cell size (defaults to 250 x 250)
    CGFloat _minimumColumnSpacing;                  // Minimum spacing between columns
    CGFloat _rowSpacing;                            // Minimum spacing between rows

    NSMutableIndexSet *_originalSelectionIndexes;   // Original set of indexes selected before an inverted (cmd key) selection operation
    NSMutableIndexSet *_selectionIndexes;           // Index or indexes that are currently selected
    NSUInteger _indexOfKeyboardSelection;           // Last index of the selected cell using the keyboard

    __unsafe_unretained id<OEGridViewDelegate> _delegate;
    __unsafe_unretained id<OEGridViewDataSource> _dataSource;

    NSMutableSet *_visibleCells;                    // Cached visible cells
    NSMutableIndexSet *_visibleCellsIndexes;        // Cached indexes of the visible cells
    NSMutableSet *_reuseableCells;                  // Cached cells that are no longer in view

    NSDraggingSession *_draggingSession;            // Drag session used during a drag operation
    OEGridLayer *_previousDragDestinationLayer;
    OEGridLayer *_dragDestinationLayer;             // Destination cell of a drag operation
    NSDragOperation _lastDragOperation;             // Last drag operation generated by -draggingEntered:
    OEGridLayer *_trackingLayer;                    // The layer receiving all the drag operations (can be root layer)
    NSPoint _initialPoint;                          // Initial position of the mouse of a drag operation

    BOOL _needsReloadData;                          // Determines if the data should be reloaded
    BOOL _needsLayoutGridView;                      // Determines if the cells should really be laid out

    NSUInteger _cachedNumberOfVisibleColumns;       // Cached number of visible columns
    NSUInteger _cachedNumberOfVisibleRows;          // Cached number of visiabl rows (include partially visible rows)
    NSUInteger _cachedNumberOfItems;                // Cached number of items in the data source

    NSPoint _cachedContentOffset;                   // Last known content offset
    NSSize _cachedViewSize;                         // Last known view size
    NSSize _cachedCellSize;                         // Cached cell size that includes row spacing and cached column spacing
    CGFloat _cachedColumnSpacing;                   // Cached column spacing is the dynamic spacing between columns, no less than minimumColumnSpacing

    OEGridViewFieldEditor *_fieldEditor;

    struct
    {
        BOOL selectionChanged : 1;
        BOOL doubleClickedCellForItemAtIndex : 1;
        BOOL validateDrop : 1;
        BOOL draggingUpdated : 1;
        BOOL acceptDrop : 1;
    } _delegateHas;                                 // Cached methods that the delegate implements

    struct
    {
        BOOL viewForNoItemsInGridView : 1;
        BOOL willBeginEditingCellForItemAtIndex : 1;
        BOOL didEndEditingCellForItemAtIndex : 1;
        BOOL pasteboardWriterForIndex : 1;
    } _dataSourceHas;                               // Cached methods that the delegate implements
}

- (id)dequeueReusableCell;
- (NSUInteger)numberOfItems;
- (OEGridViewCell *)cellForItemAtIndex:(NSUInteger)index makeIfNecessary:(BOOL)necessary;
- (NSUInteger)indexForCell:(OEGridViewCell *)cell;
- (NSUInteger)indexForCellAtPoint:(NSPoint)point;
- (NSIndexSet *)indexesForCellsInRect:(NSRect)rect;
- (NSArray *)visibleCells;
- (NSIndexSet *)indexesForVisibleCells;
- (NSUInteger)indexForSelectedCell;
- (NSIndexSet *)indexesForSelectedCells;
- (void)selectCellAtIndex:(NSUInteger)index;
- (void)deselectCellAtIndex:(NSUInteger)index;
- (void)selectAll:(id)sender;
- (void)deselectAll:(id)sender;
- (void)reloadData;
- (void)reloadCellsAtIndexes:(NSIndexSet *)indexes;
- (NSRect)rectForCellAtIndex:(NSUInteger)index;

#pragma mark - Properties
@property (nonatomic, retain) CALayer *foregroundLayer;
@property (nonatomic, retain) CALayer *backgroundLayer;
@property (nonatomic, assign) CGFloat minimumColumnSpacing;
@property (nonatomic, assign) CGFloat rowSpacing;
@property (nonatomic, assign) CGSize itemSize;
@property (nonatomic, assign) id<OEGridViewDataSource> dataSource;
@property (nonatomic, assign) id<OEGridViewDelegate> delegate;
@property (nonatomic, copy) NSIndexSet *selectionIndexes;

@end
