struct input
{
    float2 video_size;
    float2 texture_size;
    float2 output_size;
    float frame_count;
    float frame_direction;
    float frame_rotation;
};

struct output_vertex
{
    float4 position : POSITION;
    float3 color : COLOR;
    float2 texCoord : TEXCOORD0;
};

output_vertex main_vertex
(
    float4 position : POSITION,
    float3 color : COLOR,
    float2 texCoord : TEXCOORD0,
    uniform input IN,
    uniform float4x4 modelViewProj
)
{
    output_vertex OUT;
    OUT.position = mul(modelViewProj, position);
    OUT.color = color;
    OUT.texCoord = texCoord;
    return OUT;
}

struct output_fragment
{
    float4 color : COLOR;
};

output_fragment main_fragment
(
    float2 texCoord : TEXCOORD0,
    uniform samplerRECT s_p : TEXUNIT0
)
{
    output_fragment OUT;
    OUT.color = texRECT(s_p, texCoord)+float4(0.5,0.0,0.0,0.0);
    return OUT;
}