#!/usr/bin/env python
# 
# Copyright (c) 2012 FadingRed LLC
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
# Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# 

from subprocess import Popen, PIPE
import sys
import os

if __name__ == '__main__':
  if len(sys.argv) != 2:
    sys.stderr.write('Usage: %s lang\n' % sys.argv[0])
    sys.exit(1)
  lang = sys.argv[1]
  command = Popen([
    'find', '.',
    '-name', 'en.lproj',
    '-not', '-path', '*/.hg/*',
    '-not', '-path', '*/build/*'], stdout=PIPE, stderr=PIPE)
  stdout, stderr = command.communicate()
  if command.returncode == 0:
    for line in stdout.split('\n'):
      if line.strip():
        directory = os.path.dirname(line)
        newdir = os.path.join(directory, '%s.lproj' % lang)
        if not os.path.exists(newdir):
          sys.stdout.write('Creating %s\n' % newdir)
          os.mkdir(newdir)
      
  else:
    sys.stderr.write('warning: could not find lproj folders. find returned error %i\n' % command.returncode)
